# Generated by Django 5.1.1 on 2024-10-15 22:29

import django.db.models.deletion
import scripts.models
import versionfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scripts", "0028_alter_character_first_night_position_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomebrewCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_id", models.CharField(max_length=30)),
                ("character_name", models.CharField(max_length=30)),
                ("ability", models.TextField()),
                ("first_night_reminder", models.TextField(blank=True, null=True)),
                ("other_night_reminder", models.TextField(blank=True, null=True)),
                (
                    "global_reminders",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("reminders", models.TextField(blank=True, null=True)),
                (
                    "character_type",
                    models.CharField(
                        choices=[
                            ("Townsfolk", "Townsfolk"),
                            ("Outsider", "Outsider"),
                            ("Minion", "Minion"),
                            ("Demon", "Demon"),
                            ("Traveller", "Traveller"),
                            ("Fabled", "Fabled"),
                        ],
                        max_length=30,
                    ),
                ),
                ("first_night_position", models.FloatField(blank=True, null=True)),
                ("other_night_position", models.FloatField(blank=True, null=True)),
                ("image_url", models.CharField(blank=True, max_length=100, null=True)),
                ("modifies_setup", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HomebrewVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latest", models.BooleanField(default=True)),
                (
                    "script_type",
                    models.CharField(
                        choices=[("Teensyville", "Teensyville"), ("Full", "Full")],
                        default="Full",
                        max_length=20,
                    ),
                ),
                ("author", models.CharField(blank=True, max_length=100, null=True)),
                ("version", versionfield.fields.VersionField()),
                ("content", models.JSONField()),
                (
                    "pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=scripts.models.determine_script_location,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                ("num_townsfolk", models.IntegerField()),
                ("num_outsiders", models.IntegerField()),
                ("num_minions", models.IntegerField()),
                ("num_demons", models.IntegerField()),
                ("num_fabled", models.IntegerField()),
                ("num_travellers", models.IntegerField()),
                (
                    "homebrewiness",
                    models.IntegerField(
                        choices=[(0, "Hybrid"), (1, "Homebrew")], default=1
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homebrew_versions",
                        to="scripts.script",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
