services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=botcdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
  web:
    build: .
    depends_on:
      - db
    container_name: botc-scripts
    # command: "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    env_file:
      - .env
volumes:
  db: