[tool.poetry]
name = "botc-scripts"
version = "0.1.0"
description = ""
authors = ["Geoff Thomas"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.1.7"
django-versionfield = "^1.0.2"
packaging = "^20.9"
django-tables2 = "^2.3.4"
django-bootstrap4 = "^2.3.1"
django-filter = "^2.4.0"
djangorestframework = "^3.12.2"
whitenoise = "^5.2.0"
psycopg2-binary = "^2.9.1"

[tool.poetry.dev-dependencies]
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
