[tool.poetry]
name = "botc-scripts"
version = "0.1.0"
description = ""
authors = ["Geoff Thomas"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
Django = "^4.2"
django-versionfield = "^1.0.2"
packaging = "^23.1"
django-tables2 = "^2.4.1"
django-bootstrap4 = "^23.1"
django-filter = "^23.1"
djangorestframework = "^3.12.2"
psycopg2-binary = "^2.9.6"
django-storages = {version = "1.11.1", extras = ["azure"]}
django-allauth = "^0.55.0"
django-bootstrap-icons = "^0.8.2"
Babel = "^2.10.3"
django-markdownify = "^0.9.2"
fontawesomefree = "^6.4.0"
requests = "^2.31.0"
django-cors-headers = "^4.2.0"

[tool.poetry.dev-dependencies]
black = "*"
isort = "*"
mypy = "*"
uritemplate = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
exclude = 'scripts/migrations'
