[tool.poetry]
name = "botc-scripts"
version = "0.1.0"
description = ""
authors = ["Geoff Thomas"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.1.7"
django-versionfield = "^1.0.2"
packaging = "^20.9"

[tool.poetry.dev-dependencies]
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
