[tool.poetry]
name = "botc-scripts"
version = "0.1.0"
description = ""
authors = ["Geoff Thomas"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.2.18"
django-versionfield = "^1.0.2"
packaging = "^20.9"
django-tables2 = "^2.4.1"
django-bootstrap4 = "^22.3"
django-filter = "^2.4.0"
djangorestframework = "^3.12.2"
psycopg2-binary = "^2.9.1"
django-storages = {version = "1.11.1", extras = ["azure"]}
django-allauth = "^0.50.0"
django-bootstrap-icons = "^0.8.2"
Babel = "^2.10.3"
django-markdownify = "^0.9.2"
fontawesomefree = "^6.3.0"
requests = "^2.28.2"

[tool.poetry.dev-dependencies]
black = "*"
isort = "*"
mypy = "*"
uritemplate = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
exclude = 'scripts/migrations'
