# Generated by Django 3.2.5 on 2021-07-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptversion',
            name='tags',
            field=models.ManyToManyField(blank=True, to='scripts.ScriptTag'),
        ),
    ]
