# Generated by Django 3.2.10 on 2021-12-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_scriptversion_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='scripttag',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
