# Generated by Django 3.2.12 on 2022-03-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0008_alter_script_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='scripttag',
            name='style',
            field=models.CharField(choices=[('badge-primary', 'Blue'), ('badge-secondary', 'Grey'), ('badge-success', 'Green'), ('badge-danger', 'Red'), ('badge-warning', 'Yellow'), ('badge-info', 'Cyan'), ('badge-light', 'White'), ('badge-dark', 'Black')], default='badge-primary', max_length=20),
        ),
    ]
