# Generated by Django 3.2.12 on 2022-04-02 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0009_scripttag_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldCup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('vod', models.CharField(blank=True, max_length=100)),
                ('form', models.CharField(blank=True, max_length=100)),
                ('script1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scripts.scriptversion')),
                ('script2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scripts.scriptversion')),
            ],
        ),
    ]
