# Generated by Django 3.2.13 on 2022-06-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0012_auto_20220523_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldcup',
            name='winner',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Home', 'Home'), ('Away', 'Away')], default='Unknown', max_length=10),
        ),
    ]
