# Generated by Django 3.2.13 on 2022-06-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0014_comment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('friendly_language', models.CharField(max_length=20)),
                ('character_id', models.CharField(max_length=20)),
                ('character_name', models.CharField(max_length=20)),
                ('ability', models.TextField()),
                ('first_night_reminder', models.TextField(blank=True, null=True)),
                ('other_night_reminder', models.TextField(blank=True, null=True)),
                ('global_reminders', models.TextField(blank=True, null=True)),
                ('reminders', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['language', 'character_id'], name='scripts_tra_languag_477f19_idx'),
        ),
        migrations.AddConstraint(
            model_name='translation',
            constraint=models.UniqueConstraint(fields=('language', 'character_id'), name='character_language'),
        ),
    ]
