# Generated by Django 3.2.13 on 2022-06-12 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0015_auto_20220612_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translation',
            options={'permissions': [('update_translation', 'Can update a translation')]},
        ),
    ]
