# Generated by Django 3.2.16 on 2023-01-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0016_auto_20220709_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripttag',
            name='style',
            field=models.CharField(choices=[('badge-primary', 'Blue'), ('badge-secondary', 'Grey'), ('badge-success', 'Green'), ('badge-danger', 'Red'), ('badge-warning', 'Yellow'), ('badge-info', 'Cyan'), ('badge-light', 'White'), ('badge-dark', 'Black'), ('badge-purple', 'Purple')], default='badge-primary', max_length=20),
        ),
    ]
