# Generated by Django 3.2.18 on 2023-03-16 22:18

from django.db import migrations, models
from scripts.views import calculate_edition


def update_existing_scripts(apps, schema_editor):
    ScriptVersion = apps.get_model("scripts", "scriptversion")
    for script in ScriptVersion.objects.all():
        script.edition = calculate_edition(script.content)
        script.save()


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0017_alter_scripttag_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="scriptversion",
            name="edition",
            field=models.IntegerField(
                choices=[(0, "Base"), (1, "+ Kickstarter"), (2, "+ Unreleased")],
                default=0,
            ),
        ),
        migrations.RunPython(
            update_existing_scripts, reverse_code=migrations.RunPython.noop
        ),
    ]
