# Generated by Django 3.2.18 on 2023-03-19 01:14

from django.db import migrations, models


def set_default_order_field(apps, schema_editor):
    ScriptTag = apps.get_model("scripts", "scripttag")
    for tag in ScriptTag.objects.all():
        tag.order = tag.pk
        tag.save()


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0018_auto_20230316_2218"),
    ]

    operations = [
        migrations.AddField(
            model_name="scripttag",
            name="order",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RunPython(
            set_default_order_field, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="scripttag",
            name="order",
            field=models.IntegerField(unique=True),
        ),
    ]
