# Generated by Django 3.2.18 on 2023-03-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0019_scripttag_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="edition",
            field=models.IntegerField(
                choices=[
                    (0, "Base"),
                    (1, "Kickstarter"),
                    (2, "clocktower.online"),
                    (3, "All"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="scriptversion",
            name="edition",
            field=models.IntegerField(
                choices=[
                    (0, "Base"),
                    (1, "Kickstarter"),
                    (2, "clocktower.online"),
                    (3, "All"),
                ],
                default=3,
            ),
        ),
    ]
