# Generated by Django 3.2.18 on 2023-03-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0020_auto_20230319_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scriptversion',
            name='edition',
            field=models.IntegerField(choices=[(0, 'Base'), (1, 'Kickstarter'), (2, 'clocktower.online'), (3, 'All')], default=0),
        ),
    ]
