# Generated by Django 3.2.18 on 2023-04-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0022_alter_scriptversion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='scripttag',
            name='inheritable',
            field=models.BooleanField(default=False),
        ),
    ]
