# Generated by Django 3.2.18 on 2023-04-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0023_scripttag_inheritable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptversion',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
