# Generated by Django 4.2.5 on 2023-12-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scripts", "0024_alter_scriptversion_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scripttag",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
