# Generated by Django 4.2.8 on 2023-12-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scripts", "0025_alter_scripttag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scripttag",
            name="style",
            field=models.CharField(
                choices=[
                    ("badge-primary", "Blue"),
                    ("badge-secondary", "Grey"),
                    ("badge-success", "Green"),
                    ("badge-danger", "Red"),
                    ("badge-warning", "Yellow"),
                    ("badge-info", "Cyan"),
                    ("badge-light", "White"),
                    ("badge-dark", "Black"),
                    ("badge-purple", "Purple"),
                    ("badge-nocturne", "Nocturne"),
                ],
                default="badge-primary",
                max_length=20,
            ),
        ),
    ]
