# Generated by Django 5.1.1 on 2024-10-16 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0027_remove_special_characters_from_character_ids"),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Character', 
            new_name='ClocktowerCharacter',
        ),
        migrations.DeleteModel(
            name="Play",
        ),
        migrations.AlterField(
            model_name="clocktowercharacter",
            name="first_night_position",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clocktowercharacter",
            name="other_night_position",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
