# Generated by Django 5.1.1 on 2024-10-15 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0027_remove_special_characters_from_character_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="first_night_position",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="other_night_position",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scriptversion",
            name="script",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clocktower_versions",
                to="scripts.script",
            ),
        ),
        migrations.DeleteModel(
            name="Play",
        ),
    ]
