# Generated by Django 5.1.1 on 2024-10-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0028_clocktowercharacter_delete_character_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomebrewCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_id", models.CharField(max_length=30)),
                ("character_name", models.CharField(max_length=30)),
                ("ability", models.TextField()),
                ("first_night_reminder", models.TextField(blank=True, null=True)),
                ("other_night_reminder", models.TextField(blank=True, null=True)),
                (
                    "global_reminders",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("reminders", models.TextField(blank=True, null=True)),
                (
                    "character_type",
                    models.CharField(
                        choices=[
                            ("Townsfolk", "Townsfolk"),
                            ("Outsider", "Outsider"),
                            ("Minion", "Minion"),
                            ("Demon", "Demon"),
                            ("Traveller", "Traveller"),
                            ("Fabled", "Fabled"),
                            ("Unknown", "Unknown"),
                        ],
                        max_length=30,
                    ),
                ),
                ("first_night_position", models.FloatField(blank=True, null=True)),
                ("other_night_position", models.FloatField(blank=True, null=True)),
                ("image_url", models.CharField(blank=True, max_length=100, null=True)),
                ("modifies_setup", models.BooleanField(default=False)),
            ],
            options={
                "permissions": [
                    ("update_characters", "Can update character information")
                ],
            },
        ),
        migrations.AddField(
            model_name="scriptversion",
            name="homebrewiness",
            field=models.IntegerField(
                choices=[(0, "Clocktower"), (1, "Hybrid"), (2, "Homebrew")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="clocktowercharacter",
            name="character_type",
            field=models.CharField(
                choices=[
                    ("Townsfolk", "Townsfolk"),
                    ("Outsider", "Outsider"),
                    ("Minion", "Minion"),
                    ("Demon", "Demon"),
                    ("Traveller", "Traveller"),
                    ("Fabled", "Fabled"),
                    ("Unknown", "Unknown"),
                ],
                max_length=30,
            ),
        ),
    ]
