# Generated by Django 5.1.1 on 2024-10-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0029_homebrewcharacter_scriptversion_homebrewiness_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clocktowercharacter",
            name="global_reminders",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="homebrewcharacter",
            name="global_reminders",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="translation",
            name="global_reminders",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
