# Generated by Django 5.1.2 on 2024-11-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0030_alter_clocktowercharacter_global_reminders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clocktowercharacter',
            name='character_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clocktowercharacter',
            name='character_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='homebrewcharacter',
            name='character_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='homebrewcharacter',
            name='character_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='translation',
            name='character_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='translation',
            name='character_name',
            field=models.CharField(max_length=30),
        ),
    ]
