# Generated by Django 5.1.2 on 2024-11-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0031_alter_clocktowercharacter_character_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clocktowercharacter',
            name='id',
        ),
        migrations.RemoveField(
            model_name='homebrewcharacter',
            name='id',
        ),
        migrations.AlterField(
            model_name='clocktowercharacter',
            name='character_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clocktowercharacter',
            name='global_reminders',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clocktowercharacter',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homebrewcharacter',
            name='character_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='homebrewcharacter',
            name='global_reminders',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homebrewcharacter',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='translation',
            name='global_reminders',
            field=models.TextField(blank=True, null=True),
        ),
    ]
