# Generated by Django 5.1.4 on 2025-02-26 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0032_remove_clocktowercharacter_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebrewcharacter',
            name='script',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scripts.script'),
        ),
    ]
