# Generated by Django 5.2.3 on 2025-06-13 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0033_homebrewcharacter_script'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clocktowercharacter',
            name='image_url',
        ),
    ]
