# Generated by Django 5.2.4 on 2025-07-06 13:37

import django.db.models.deletion
from django.db import migrations, models

def change_parent():
    from scripts.models import Favourite, Vote

    # Update existing favourites and votes to have the parent field set to the script they belong to
    for favourite in Favourite.objects.all():
        favourite.parent = favourite.script.script
        favourite.save()

    for vote in Vote.objects.all():
        vote.parent = vote.script.script
        vote.save()

class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0034_remove_clocktowercharacter_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='scripts.script'),
        ),
        migrations.AddField(
            model_name='vote',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='scripts.script'),
        ),
        migrations.AlterField(
            model_name='clocktowercharacter',
            name='edition',
            field=models.IntegerField(choices=[(0, 'Base'), (1, 'Kickstarter'), (2, 'Carousel'), (3, 'All')]),
        ),
        migrations.AlterField(
            model_name='scriptversion',
            name='edition',
            field=models.IntegerField(choices=[(0, 'Base'), (1, 'Kickstarter'), (2, 'Carousel'), (3, 'All')], default=3),
        ),
        migrations.RunPython(
            change_parent,
            reverse_code=migrations.RunPython.noop,  # No reverse migration needed
        )
    ]
