# Generated by Django 5.2.4 on 2025-07-06 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0036_migrate_edition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='script',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='script',
        ),
    ]
