# Generated by Django 5.2.4 on 2025-07-15 21:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0037_remove_favourite_script_remove_vote_script'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scripttag',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('parent', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('parent', 'user')},
        ),
        migrations.AddIndex(
            model_name='clocktowercharacter',
            index=models.Index(fields=['character_type'], name='cchar_character_type_idx'),
        ),
        migrations.AddIndex(
            model_name='clocktowercharacter',
            index=models.Index(fields=['character_id'], name='cchar_character_id_idx'),
        ),
        migrations.AddIndex(
            model_name='clocktowercharacter',
            index=models.Index(fields=['edition'], name='cchar_edition_idx'),
        ),
        migrations.AddIndex(
            model_name='favourite',
            index=models.Index(fields=['parent'], name='favourite_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='favourite',
            index=models.Index(fields=['user'], name='favourite_user_idx'),
        ),
        migrations.AddIndex(
            model_name='homebrewcharacter',
            index=models.Index(fields=['character_type'], name='hchar_character_type_idx'),
        ),
        migrations.AddIndex(
            model_name='homebrewcharacter',
            index=models.Index(fields=['character_id'], name='hchar_character_id_idx'),
        ),
        migrations.AddIndex(
            model_name='script',
            index=models.Index(fields=['name'], name='script_name_idx'),
        ),
        migrations.AddIndex(
            model_name='script',
            index=models.Index(fields=['owner'], name='script_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='scripttag',
            index=models.Index(fields=['name'], name='scripttag_name_idx'),
        ),
        migrations.AddIndex(
            model_name='scripttag',
            index=models.Index(fields=['public'], name='scripttag_public_idx'),
        ),
        migrations.AddIndex(
            model_name='scripttag',
            index=models.Index(fields=['inheritable'], name='scripttag_inheritable_idx'),
        ),
        migrations.AddIndex(
            model_name='scriptversion',
            index=models.Index(fields=['script'], name='sv_script_idx'),
        ),
        migrations.AddIndex(
            model_name='scriptversion',
            index=models.Index(fields=['latest'], name='sv_latest_idx'),
        ),
        migrations.AddIndex(
            model_name='scriptversion',
            index=models.Index(fields=['homebrewiness'], name='sv_homebrewiness_idx'),
        ),
        migrations.AddIndex(
            model_name='scriptversion',
            index=models.Index(fields=['edition'], name='sv_edition_idx'),
        ),
        migrations.AddIndex(
            model_name='scriptversion',
            index=models.Index(fields=['num_demons'], name='sv_num_demons_idx'),
        ),
        migrations.AddIndex(
            model_name='scriptversion',
            index=models.Index(fields=['script', 'version'], name='sv_script_and_version_idx'),
        ),
        migrations.AddIndex(
            model_name='scriptversion',
            index=models.Index(fields=['latest', 'homebrewiness'], name='sv_latest_and_homebrew_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['parent'], name='vote_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['user'], name='vote_user_idx'),
        ),
    ]
