# Generated by Django 5.2.4 on 2025-08-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0038_alter_scripttag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripttag',
            name='style',
            field=models.CharField(choices=[('badge-primary', 'Blue'), ('badge-secondary', 'Grey'), ('badge-success', 'Green'), ('badge-danger', 'Red'), ('badge-warning', 'Yellow'), ('badge-info', 'Cyan'), ('badge-light', 'White'), ('badge-dark', 'Black'), ('badge-purple', 'Purple'), ('badge-nocturne', 'Nocturne'), ('badge-bloodred', 'Bloodred')], default='badge-primary', max_length=20),
        ),
    ]
