# Generated by Django 5.2.4 on 2025-08-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0039_alter_scripttag_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clocktowercharacter',
            name='character_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='homebrewcharacter',
            name='character_name',
            field=models.CharField(max_length=30),
        ),
    ]
