# Generated by Django 5.2.4 on 2025-08-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0040_alter_clocktowercharacter_character_name_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scripttag',
            index=models.Index(fields=['order'], name='scripttag_order_idx'),
        ),
    ]
