# Generated by Django 5.2.6 on 2025-09-09 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0041_scripttag_scripttag_order_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scriptversion',
            options={'permissions': [('download_unsupported_json', 'Can the request the download of a JSON that replaces unsupported characters'), ('api_write_permission', 'Can create, update or delete scripts via the API. This is not required for reading scripts.')]},
        ),
    ]
