# Generated by Django 5.1 on 2024-12-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0041_scripttag_scripttag_order_idx'),
    ]

    operations = [
        # Add composite index for commonly queried fields
        migrations.AddIndex(
            model_name='scriptversion',
            index=models.Index(fields=['latest', 'script_type'], name='sv_latest_type_idx'),
        ),
        
        # Add index for created date (for time-based queries)
        migrations.AddIndex(
            model_name='scriptversion',
            index=models.Index(fields=['created'], name='sv_created_idx'),
        ),
        
        # Add composite index for votes
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['parent', 'created'], name='vote_parent_created_idx'),
        ),
        
        # Add composite index for favourites
        migrations.AddIndex(
            model_name='favourite',
            index=models.Index(fields=['parent', 'user'], name='fav_parent_user_idx'),
        ),
        
        # Add index for comments
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['script', 'created'], name='comment_script_created_idx'),
        ),
        
        # Add index for parent comments
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent'], name='comment_parent_idx'),
        ),
        
        # Add GIN index for JSONB content field (PostgreSQL specific)
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS sv_content_gin_idx ON scripts_scriptversion USING gin (content);",
            reverse_sql="DROP INDEX IF EXISTS sv_content_gin_idx;",
        ),
    ]
