# Generated by Django 5.2.6 on 2025-09-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0042_alter_scriptversion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='num_downloads',
            field=models.IntegerField(default=0),
        ),
    ]
