# Generated by Django 5.2.7 on 2025-10-31 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0043_script_num_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptversion',
            name='num_loric',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clocktowercharacter',
            name='character_type',
            field=models.CharField(choices=[('Townsfolk', 'Townsfolk'), ('Outsider', 'Outsider'), ('Minion', 'Minion'), ('Demon', 'Demon'), ('Traveller', 'Traveller'), ('Fabled', 'Fabled'), ('Loric', 'Loric'), ('Unknown', 'Unknown')], max_length=30),
        ),
        migrations.AlterField(
            model_name='homebrewcharacter',
            name='character_type',
            field=models.CharField(choices=[('Townsfolk', 'Townsfolk'), ('Outsider', 'Outsider'), ('Minion', 'Minion'), ('Demon', 'Demon'), ('Traveller', 'Traveller'), ('Fabled', 'Fabled'), ('Loric', 'Loric'), ('Unknown', 'Unknown')], max_length=30),
        ),
    ]
