# Generated by Django 5.2.13 on 2026-04-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0044_scriptversion_num_loric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripttag',
            name='style',
            field=models.CharField(choices=[('badge-primary', 'Blue'), ('badge-secondary', 'Grey'), ('badge-success', 'Green'), ('badge-danger', 'Red'), ('badge-warning', 'Yellow'), ('badge-info', 'Cyan'), ('badge-light', 'White'), ('badge-dark', 'Black'), ('badge-purple', 'Purple'), ('badge-nocturne', 'Nocturne'), ('badge-bloodred', 'Bloodred'), ('badge-clockconaus', 'Clockconaus')], default='badge-primary', max_length=20),
        ),
    ]
