# Generated by Django 5.2.17 on 2026-08-31 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0046_scriptversion_sv_content_gin_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptVersionCharacter',
            fields=[
                ('pk', models.CompositePrimaryKey('script_version', 'character_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('character_id', models.TextField()),
                ('script_version', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='scripts.scriptversion')),
            ],
            options={
                'indexes': [models.Index(fields=['character_id'], name='svc_character_id_idx')],
            },
        ),
    ]
