# Generated by Django 5.2.17 on 2026-09-22 08:36

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0047_enable_pg_trgm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='script',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='script_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='scriptversion',
            index=models.Index(fields=['num_townsfolk'], name='sv_num_townsfolk_idx'),
        ),
        migrations.AddIndex(
            model_name='scriptversion',
            index=models.Index(fields=['num_outsiders'], name='sv_num_outsiders_idx'),
        ),
        migrations.AddIndex(
            model_name='scriptversion',
            index=models.Index(fields=['num_minions'], name='sv_num_minions_idx'),
        ),
        migrations.AddIndex(
            model_name='scriptversion',
            index=models.Index(fields=['num_fabled'], name='sv_num_fabled_idx'),
        ),
        migrations.AddIndex(
            model_name='scriptversion',
            index=models.Index(fields=['num_loric'], name='sv_num_loric_idx'),
        ),
        migrations.AddIndex(
            model_name='scriptversion',
            index=models.Index(fields=['num_travellers'], name='sv_num_travellers_idx'),
        ),
        migrations.AddIndex(
            model_name='scriptversion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['author'], name='sv_author_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
