# A list of constants that should be consistent across database/form usage
MAX_SCRIPT_NAME_LENGTH = 100
MAX_AUTHOR_NAME_LENGTH = 100
STANDARD_TEENSYVILLE_CHARACTER_COUNT = 12
MAX_CHARACTER_COUNT = 25

MAX_JSON_UPLOAD_BYTES = 1024 * 1024
MAX_PDF_UPLOAD_BYTES = 10 * 1024 * 1024
MAX_UPLOAD_REQUEST_BYTES = MAX_JSON_UPLOAD_BYTES + MAX_PDF_UPLOAD_BYTES + 1024 * 1024
